using System;
using System.Windows.Forms;
using UPPY.Desktop.Interfaces.Controllers;
using UPPY.Desktop.Interfaces.Controllers.TechRoutes;

namespace UPPY.Desktop.Views.TechRoutes
{
    public partial class TechRoutesListForm : Form
    {
        private readonly ITechRouteListController _techRouteController;

        public TechRoutesListForm(ITechRouteListController techRouteController)
        {
            _techRouteController = techRouteController;
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gcTechRoutes.DataSource = _techRouteController.GetData();
            _techRouteController.DataRefreshed += _techRouteController_DataRefreshed;
        }

        void _techRouteController_DataRefreshed(object sender, EventArgs e)
        {
            gcTechRoutes.DataSource = _techRouteController.GetData();
            gcTechRoutes.RefreshDataSource();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            var newDoc = _techRouteController.CreateDocument();
            _techRouteController.EditDocument(newDoc);
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            var doc = (Core.DomainModel.TechRoute) gvTechRoutes.GetFocusedRow();
            _techRouteController.EditDocument(doc);
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            var doc = (Core.DomainModel.TechRoute)gvTechRoutes.GetFocusedRow();
             _techRouteController.Delete(doc);
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            
        }
    }
}