using System.Collections.Generic;
using System.Windows.Forms;
using Core.DomainModel;
using DesktopApp.Infrastructure;
using DesktopApp.Interfaces;

namespace DesktopApp.Forms
{
    public partial class StandartEditForm : Form, IDocEditForm<Standart>
    {
        private Standart _document;

        public StandartEditForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new System.Collections.Generic.List<Core.DomainModel.PostitionStandart>();
        
        }

        public Standart Document
        {
            get { return _document; }
            set { _document = value; }
        }

        public event DocumentEventHandler<Standart> UpdateDocument;
    }
}