using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Core.DomainModel;
using DesktopApp.Interfaces;

namespace DesktopApp.Forms
{
    public partial class TechRoutesListForm : Form, IDocsListForm<TechRoute>
    {
        private readonly IController<TechRoute> _techRouteController;

        public TechRoutesListForm(IController<TechRoute> techRouteController)
        {
            _techRouteController = techRouteController;
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = _techRouteController.GetData();
        }

        public IController<TechRoute> Controller
        {
            get { return _techRouteController; }
        }
    }
}
