using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Core;
using MongoWork;

namespace DesktopApp
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            treeList1.DataSource = new System.Collections.Generic.List<Core.Drawing>();
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void MainForm_Load(object sender, EventArgs e)
        {
            MongoWork.MongoDbInitializer dbInitializer = new MongoDbInitializer();
            dbInitializer.ConnectToDb();
            // dbInitializer.InitDatabase();

            MongoDbConnector connector = new MongoDbConnector(dbInitializer.GetDbConnection());
            var drawings = connector.GetListCollection<Drawing>();
            drawingBindingSource.DataSource = drawings.Where(x => x.ParentId == null);
            treeList1.DataSource = drawings;
            treeList1.Refresh();

            rProfile.Items.AddRange(drawings.Select(x => x.Profile).Where(x => !string.IsNullOrWhiteSpace(x)).Distinct().ToList());
        }

        private void treeList1_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        {

        }

        private void treeList1_FilterNode(object sender, DevExpress.XtraTreeList.FilterNodeEventArgs e)
        {
            if (e.Node.HasChildren)
            {
                e.Node.Visible = true;
                e.Handled = true;
            }
        }
    }
}
