//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Head {
    
    private string aRTPartIDField;
    
    private string aRTZNrField;
    
    private string aRTWeightCField;
    
    private string aRTPartIDoldField;
    
    private string aRTTKGrp2Field;
    
    private string aRTDateCreField;
    
    private string aRTDateCngField;
    
    private string aRTUserCreField;
    
    private string aRTProjNoField;
    
    private string aRTMfgNoField;
    
    private string aRTProjectField;
    
    private string aRTUserChkField;
    
    private string aRTTypField;
    
    private string aRTKSLVertField;
    
    private string aRTStatusField;
    
    private string aRTWtKZField;
    
    private string aRTBOMTypField;
    
    private string aRTMatArtField;
    
    private string aRTPartVersionField;
    
    private string aRTValFromField;
    
    private string aRTValUntilField;
    
    private string aRTDateRelField;
    
    private string aRTTKGrp1Field;
    
    private string aRTUserModField;
    
    private string aRTDateLastRelField;
    
    private string aRTLSNField;
    
    private string aRTDeliverLField;
    
    private string aRTDeliverWField;
    
    private string aRTNameField;

    private string aRTNameRemField;
    
    private string aRTPartTypField;
    
    private string aRTESNField;
    
    private string aRTUnitField;
    
    private string aRTWeightUnitField;
    
    private string aRTWeightField;
    
    private string aRTWeightKeyField;
    
    private string aRTStdDesField;
    
    private string aRTTypNormField;
    
    private string aRTNormField;
    
    private string aRTMaterialField;
    
    private string aRTSurfaceField;
    
    private string aRTMatTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.PartID")]
    public string ARTPartID {
        get {
            return this.aRTPartIDField;
        }
        set {
            this.aRTPartIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.ZNr")]
    public string ARTZNr {
        get {
            return this.aRTZNrField;
        }
        set {
            this.aRTZNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.WeightC")]
    public string ARTWeightC {
        get {
            return this.aRTWeightCField;
        }
        set {
            this.aRTWeightCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.PartIDold")]
    public string ARTPartIDold {
        get {
            return this.aRTPartIDoldField;
        }
        set {
            this.aRTPartIDoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.TKGrp2")]
    public string ARTTKGrp2 {
        get {
            return this.aRTTKGrp2Field;
        }
        set {
            this.aRTTKGrp2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DateCre")]
    public string ARTDateCre {
        get {
            return this.aRTDateCreField;
        }
        set {
            this.aRTDateCreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DateCng")]
    public string ARTDateCng {
        get {
            return this.aRTDateCngField;
        }
        set {
            this.aRTDateCngField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.UserCre")]
    public string ARTUserCre {
        get {
            return this.aRTUserCreField;
        }
        set {
            this.aRTUserCreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.ProjNo")]
    public string ARTProjNo {
        get {
            return this.aRTProjNoField;
        }
        set {
            this.aRTProjNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.MfgNo")]
    public string ARTMfgNo {
        get {
            return this.aRTMfgNoField;
        }
        set {
            this.aRTMfgNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Project")]
    public string ARTProject {
        get {
            return this.aRTProjectField;
        }
        set {
            this.aRTProjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.UserChk")]
    public string ARTUserChk {
        get {
            return this.aRTUserChkField;
        }
        set {
            this.aRTUserChkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Typ")]
    public string ARTTyp {
        get {
            return this.aRTTypField;
        }
        set {
            this.aRTTypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.KSLVert")]
    public string ARTKSLVert {
        get {
            return this.aRTKSLVertField;
        }
        set {
            this.aRTKSLVertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Status")]
    public string ARTStatus {
        get {
            return this.aRTStatusField;
        }
        set {
            this.aRTStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.WtKZ")]
    public string ARTWtKZ {
        get {
            return this.aRTWtKZField;
        }
        set {
            this.aRTWtKZField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.BOMTyp")]
    public string ARTBOMTyp {
        get {
            return this.aRTBOMTypField;
        }
        set {
            this.aRTBOMTypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.MatArt")]
    public string ARTMatArt {
        get {
            return this.aRTMatArtField;
        }
        set {
            this.aRTMatArtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.PartVersion")]
    public string ARTPartVersion {
        get {
            return this.aRTPartVersionField;
        }
        set {
            this.aRTPartVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.ValFrom")]
    public string ARTValFrom {
        get {
            return this.aRTValFromField;
        }
        set {
            this.aRTValFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.ValUntil")]
    public string ARTValUntil {
        get {
            return this.aRTValUntilField;
        }
        set {
            this.aRTValUntilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DateRel")]
    public string ARTDateRel {
        get {
            return this.aRTDateRelField;
        }
        set {
            this.aRTDateRelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.TKGrp1")]
    public string ARTTKGrp1 {
        get {
            return this.aRTTKGrp1Field;
        }
        set {
            this.aRTTKGrp1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.UserMod")]
    public string ARTUserMod {
        get {
            return this.aRTUserModField;
        }
        set {
            this.aRTUserModField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DateLastRel")]
    public string ARTDateLastRel {
        get {
            return this.aRTDateLastRelField;
        }
        set {
            this.aRTDateLastRelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.LSN")]
    public string ARTLSN {
        get {
            return this.aRTLSNField;
        }
        set {
            this.aRTLSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DeliverL")]
    public string ARTDeliverL {
        get {
            return this.aRTDeliverLField;
        }
        set {
            this.aRTDeliverLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.DeliverW")]
    public string ARTDeliverW {
        get {
            return this.aRTDeliverWField;
        }
        set {
            this.aRTDeliverWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Name")]
    public string ARTName {
        get {
            return this.aRTNameField;
        }
        set {
            this.aRTNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.NameRem")]
    public string ARTNameRem
    {
        get
        {
            return this.aRTNameRemField;
        }
        set
        {
            this.aRTNameRemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.PartTyp")]
    public string ARTPartTyp {
        get {
            return this.aRTPartTypField;
        }
        set {
            this.aRTPartTypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.ESN")]
    public string ARTESN {
        get {
            return this.aRTESNField;
        }
        set {
            this.aRTESNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Unit")]
    public string ARTUnit {
        get {
            return this.aRTUnitField;
        }
        set {
            this.aRTUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.WeightUnit")]
    public string ARTWeightUnit {
        get {
            return this.aRTWeightUnitField;
        }
        set {
            this.aRTWeightUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Weight")]
    public string ARTWeight {
        get {
            return this.aRTWeightField;
        }
        set {
            this.aRTWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.WeightKey")]
    public string ARTWeightKey {
        get {
            return this.aRTWeightKeyField;
        }
        set {
            this.aRTWeightKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.StdDes")]
    public string ARTStdDes {
        get {
            return this.aRTStdDesField;
        }
        set {
            this.aRTStdDesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.TypNorm")]
    public string ARTTypNorm {
        get {
            return this.aRTTypNormField;
        }
        set {
            this.aRTTypNormField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Norm")]
    public string ARTNorm {
        get {
            return this.aRTNormField;
        }
        set {
            this.aRTNormField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Material")]
    public string ARTMaterial {
        get {
            return this.aRTMaterialField;
        }
        set {
            this.aRTMaterialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.Surface")]
    public string ARTSurface {
        get {
            return this.aRTSurfaceField;
        }
        set {
            this.aRTSurfaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ART.MatText")]
    public string ARTMatText {
        get {
            return this.aRTMatTextField;
        }
        set {
            this.aRTMatTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Position {
    
    private string aRTARTPosNoField;
    
    private string aRTARTPartIDField;
    
    private string aRTARTUnitField;
    
    private string aRTARTQuantField;
    
    private string aRTARTPosTypField;
    
    private string aRTARTPosNameField;
    
    private string aRTARTRemField;
    
    private string aRTARTVarDimField;
    
    private string aRTARTPosWeightField;
    
    private string aRTARTPosVPField;
    
    private string aRTARTRIField;
    
    private string aRTARTPosVerField;
    
    private string aRTARTStdDesField;
    
    private string aRTARTSZNoField;
    
    private string aRTARTPosVFAField;
    
    private string aRTARTPosZBLField;
    
    private string aRTARTPosMKField;
    
    private string aRTARTLtNormLocLn5Field;
    
    private string aRTMATWerkstoffIDField;
    
    private string aRTMATWerkstoffBezField;
    
    private string aRTDOCDocIDField;
    
    private string aRTDOCDocArtField;
    
    private string aRTDOCDocAusfField;
    
    private string aRTDOCSheetNoField;
    
    private string aRTDOCVersionField;
    
    private string aRTDOCNameField;
    
    private string aRTDOCLevIndField;
    
    private string aRTDOCManualField;
    
    private string aRTDOCSupplField;
    
    private string aRTDOCCustoField;
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosNo")]
    public string ARTARTPosNo {
        get {
            return this.aRTARTPosNoField;
        }
        set {
            this.aRTARTPosNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PartID")]
    public string ARTARTPartID {
        get {
            return this.aRTARTPartIDField;
        }
        set {
            this.aRTARTPartIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.Unit")]
    public string ARTARTUnit {
        get {
            return this.aRTARTUnitField;
        }
        set {
            this.aRTARTUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.Quant")]
    public string ARTARTQuant {
        get {
            return this.aRTARTQuantField;
        }
        set {
            this.aRTARTQuantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosTyp")]
    public string ARTARTPosTyp {
        get {
            return this.aRTARTPosTypField;
        }
        set {
            this.aRTARTPosTypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosName")]
    public string ARTARTPosName {
        get {
            return this.aRTARTPosNameField;
        }
        set {
            this.aRTARTPosNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.Rem")]
    public string ARTARTRem {
        get {
            return this.aRTARTRemField;
        }
        set {
            this.aRTARTRemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.VarDim")]
    public string ARTARTVarDim {
        get {
            return this.aRTARTVarDimField;
        }
        set {
            this.aRTARTVarDimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosWeight")]
    public string ARTARTPosWeight {
        get {
            return this.aRTARTPosWeightField;
        }
        set {
            this.aRTARTPosWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosVP")]
    public string ARTARTPosVP {
        get {
            return this.aRTARTPosVPField;
        }
        set {
            this.aRTARTPosVPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.RI")]
    public string ARTARTRI {
        get {
            return this.aRTARTRIField;
        }
        set {
            this.aRTARTRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosVer")]
    public string ARTARTPosVer {
        get {
            return this.aRTARTPosVerField;
        }
        set {
            this.aRTARTPosVerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.StdDes")]
    public string ARTARTStdDes {
        get {
            return this.aRTARTStdDesField;
        }
        set {
            this.aRTARTStdDesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.SZNo")]
    public string ARTARTSZNo {
        get {
            return this.aRTARTSZNoField;
        }
        set {
            this.aRTARTSZNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosVFA")]
    public string ARTARTPosVFA {
        get {
            return this.aRTARTPosVFAField;
        }
        set {
            this.aRTARTPosVFAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosZBL")]
    public string ARTARTPosZBL {
        get {
            return this.aRTARTPosZBLField;
        }
        set {
            this.aRTARTPosZBLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosMK")]
    public string ARTARTPosMK {
        get {
            return this.aRTARTPosMKField;
        }
        set {
            this.aRTARTPosMKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.LtNormLocLn5")]
    public string ARTARTLtNormLocLn5 {
        get {
            return this.aRTARTLtNormLocLn5Field;
        }
        set {
            this.aRTARTLtNormLocLn5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTMAT.WerkstoffID")]
    public string ARTMATWerkstoffID {
        get {
            return this.aRTMATWerkstoffIDField;
        }
        set {
            this.aRTMATWerkstoffIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTMAT.WerkstoffBez")]
    public string ARTMATWerkstoffBez {
        get {
            return this.aRTMATWerkstoffBezField;
        }
        set {
            this.aRTMATWerkstoffBezField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.DocID")]
    public string ARTDOCDocID {
        get {
            return this.aRTDOCDocIDField;
        }
        set {
            this.aRTDOCDocIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.DocArt")]
    public string ARTDOCDocArt {
        get {
            return this.aRTDOCDocArtField;
        }
        set {
            this.aRTDOCDocArtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.DocAusf")]
    public string ARTDOCDocAusf {
        get {
            return this.aRTDOCDocAusfField;
        }
        set {
            this.aRTDOCDocAusfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.SheetNo")]
    public string ARTDOCSheetNo {
        get {
            return this.aRTDOCSheetNoField;
        }
        set {
            this.aRTDOCSheetNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.Version")]
    public string ARTDOCVersion {
        get {
            return this.aRTDOCVersionField;
        }
        set {
            this.aRTDOCVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.Name")]
    public string ARTDOCName {
        get {
            return this.aRTDOCNameField;
        }
        set {
            this.aRTDOCNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.LevInd")]
    public string ARTDOCLevInd {
        get {
            return this.aRTDOCLevIndField;
        }
        set {
            this.aRTDOCLevIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.Manual")]
    public string ARTDOCManual {
        get {
            return this.aRTDOCManualField;
        }
        set {
            this.aRTDOCManualField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.Suppl")]
    public string ARTDOCSuppl {
        get {
            return this.aRTDOCSupplField;
        }
        set {
            this.aRTDOCSupplField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTDOC.Custo")]
    public string ARTDOCCusto {
        get {
            return this.aRTDOCCustoField;
        }
        set {
            this.aRTDOCCustoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ARTART.FS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassA", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassB", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassD", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassG", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassH", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassI", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassK", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassL", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.MassM", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.PosText", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.RM1", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.RM2", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.RM3", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ARTART.RMME", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.FS")]
    ARTARTFS,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassA")]
    ARTARTMassA,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassB")]
    ARTARTMassB,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassC")]
    ARTARTMassC,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassD")]
    ARTARTMassD,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassE")]
    ARTARTMassE,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassF")]
    ARTARTMassF,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassG")]
    ARTARTMassG,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassH")]
    ARTARTMassH,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassI")]
    ARTARTMassI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassK")]
    ARTARTMassK,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassL")]
    ARTARTMassL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.MassM")]
    ARTARTMassM,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.PosText")]
    ARTARTPosText,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.RM1")]
    ARTARTRM1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.RM2")]
    ARTARTRM2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.RM3")]
    ARTARTRM3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ARTART.RMME")]
    ARTARTRMME,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BOM {
    
    private Position[] positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Position")]
    public Position[] Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MATTXT {
    
    private Position[] positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Position")]
    public Position[] Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DOCUMENTS {
    
    private Position[] positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Position")]
    public Position[] Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Article {
    
    private Head headField;
    
    private Position[] bOMField;
    
    private Position[] mATTXTField;
    
    private Position[] dOCUMENTSField;
    
    /// <remarks/>
    public Head Head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Position", IsNullable=false)]
    public Position[] BOM {
        get {
            return this.bOMField;
        }
        set {
            this.bOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Position", IsNullable=false)]
    public Position[] MATTXT {
        get {
            return this.mATTXTField;
        }
        set {
            this.mATTXTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Position", IsNullable=false)]
    public Position[] DOCUMENTS {
        get {
            return this.dOCUMENTSField;
        }
        set {
            this.dOCUMENTSField = value;
        }
    }
}
